routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('dashboard', 'DashboardController@index')->middleware('auth.basic');
Route::get('dashboard/reporting', 'DashboardController@reportingIndex')->middleware('auth.basic');
Route::get('reporting/CA-use-tax-report', 'ReportsController@caUseTaxReport')->middleware('auth.basic');
Route::post('reporting/CA-use-tax-report', 'ReportsController@caUseTaxReport')->middleware('auth.basic');

Route::get('reporting/taxable_per_state_and_product', 'ReportsController@taxablePerStateAndProduct')->middleware('auth.basic');
Route::post('reporting/taxable_per_state_and_product', 'ReportsController@taxablePerStateAndProduct')->middleware('auth.basic');
Route::get('reporting/taxable_per_state_and_product/csv', 'ReportsController@taxablePerStateAndProductExport')->middleware('auth.basic');

Route::get('reporting/products_detailed', 'ReportsController@productsDetailed')->middleware('auth.basic');
Route::post('reporting/products_detailed', 'ReportsController@productsDetailed')->middleware('auth.basic');
Route::get('reporting/products_detailed/csv', 'ReportsController@productsDetailedExport')->middleware('auth.basic');

Route::get('reporting/rcpar_nps_log', 'ReportsController@rcparNpsLog')->middleware('auth.basic');
Route::post('reporting/rcpar_nps_log', 'ReportsController@rcparNpsLog')->middleware('auth.basic');
Route::get('reporting/rcpar_nps_log/csv', 'ReportsController@rcparNpsLogExport')->middleware('auth.basic');

Route::get('reporting/taxes_by_city', 'ReportsController@taxesByCity')->middleware('auth.basic');
Route::post('reporting/taxes_by_city', 'ReportsController@taxesByCity')->middleware('auth.basic');
Route::get('reporting/taxes_by_city/csv', 'ReportsController@taxesByCityExport')->middleware('auth.basic');

Route::get('reporting/intacct-report', 'ReportsController@intacctReport')->middleware('auth.basic');
Route::post('reporting/intacct-report', 'ReportsController@intacctReport')->middleware('auth.basic');
Route::get('reporting/intacct-report/csv', 'ReportsController@intacctReportExport')->middleware('auth.basic');

Route::get('api/process/{dataModel}', 'DataImportController@loadCSV')->middleware('auth.basic');

Route::resource('partners', 'PartnerProfilesController')->middleware('auth.basic');
Route::post('partners', 'PartnerProfilesController@index')->middleware('auth.basic');
Route::resource('user_profiles', 'UserProfilesController')->middleware('auth.basic');
Route::resource('orders', 'OrdersController')->middleware('auth.basic');

Route::get('/signin', 'AuthController@signin')->middleware('auth.basic');
Route::get('/ra/authorize', 'AuthController@gettoken')->middleware('auth.basic');
Route::get('/mail', 'OutlookController@mail')->name('mail')->middleware('auth.basic');

Route::get('system/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth.basic');

Route::get('/', function () {
  return redirect('dashboard');
});

resources/views/partners/index.blade.php
@extends('layouts.dashboard')

@section('content')

    <h1>Partners List</h1>
      <div class="panel panel-default">
        
        @if (session('status'))
        <div class="alert alert-success">
          {{ session('status') }}
        </div>
        @endif

            <div class="container filters">
                {{ Form::open(array('action' => array('PartnerProfilesController@index')) ) }}
                <div class="row">
                    <div class="col-md-2">
                        {{ Form::label('partner_name', 'Partner name') }}
                        {{ Form::text('partner_name', $filters['partner_name']) }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        {{Form::submit('submit', ['class'=>'btn btn-primary'])}}
                    </div>
                </div>
                {{ Form::close() }}
            </div>
          <div class="panel-heading">
              Partners:
          </div>

        @if (count($partners) > 0)

          <div class="panel-body">
              <table class="table table-striped task-table">
                  <!-- Table Headings -->
                  <thead>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Account Name</th>
                  </thead>
                  <!-- Table Body -->
                  <tbody>
                      @foreach ($partners as $p)
                          <tr>
                              <!-- Task Name -->
                              <td class="table-text">
                                  <div><a href="{{ route('partners.show', $p->nid) }}">{{ $p->nid }}</a></div>
                              </td>
                              <td class="table-text">
                                  <div><a href="{{ route('partners.show', $p->nid) }}">{{ $p->partner_name }}</a></div>
                              </td>
                              <td class="table-text">
                                  <div>{{ $p->account_name }}</div>
                              </td>
                          </tr>
                      @endforeach
                  </tbody>
              </table>
              <div class="pagination">
                  {{$partners->appends([
                    'partner_name' => $filters['partner_name']
                   ])->links()}}
              </div>
          </div>
        @endif

      </div>

@endsection

resources/views/partners/show.blade.php
@extends('layouts.dashboard')

@section('content')

<h1>Partner: {{ $partner->partner_name }}</h1>

  <div class="panel panel-default">

    @if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>
    @endif

      <div class="panel-heading">
          Users:
      </div>

      <div class="panel-body">
          @if (count($users) > 0)
              <table class="table table-striped task-table">
                  <!-- Table Headings -->
                  <thead>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Roles</th>
                  <th>Registration Date</th>
                  </thead>
                  <!-- Table Body -->
                  <tbody>
                  @foreach ($users as $u)
                      <tr>
                          <!-- Task Name -->
                          <td class="table-text">
                              <div><a href="{{ route('user_profiles.show', $u->uid) }}">#{{ $u->uid }}</a></div>
                          </td>
                          <td class="table-text">
                              <div>
                                  <a href="{{ route('user_profiles.show', $u->uid) }}">
                                      {{ $u->first_name }} {{ $u->last_name }}
                                  </a>
                              </div>
                          </td>
                          <td class="table-text">
                              <div>{{ $u->mail }}</div>
                          </td>
                          <td class="table-text">
                              <div>{{ $u->roles }}</div>
                          </td>
                          <td class="table-text">
                              <div>{{date('d/m/Y - h:m', strtotime($u->registration_date)) }}</div>
                          </td>
                      </tr>
                  @endforeach
                  </tbody>
              </table>
              <div class="pagination">
                  {{$users->appends([])->links()}}
              </div>
          @endif
      </div>
  </div>

  
@endsection