routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('dashboard', 'DashboardController@index')->middleware('auth.basic');
Route::get('dashboard/reporting', 'DashboardController@reportingIndex')->middleware('auth.basic');
Route::get('reporting/CA-use-tax-report', 'ReportsController@caUseTaxReport')->middleware('auth.basic');
Route::post('reporting/CA-use-tax-report', 'ReportsController@caUseTaxReport')->middleware('auth.basic');

Route::get('reporting/taxable_per_state_and_product', 'ReportsController@taxablePerStateAndProduct')->middleware('auth.basic');
Route::post('reporting/taxable_per_state_and_product', 'ReportsController@taxablePerStateAndProduct')->middleware('auth.basic');
Route::get('reporting/taxable_per_state_and_product/csv', 'ReportsController@taxablePerStateAndProductExport')->middleware('auth.basic');

Route::get('reporting/products_detailed', 'ReportsController@productsDetailed')->middleware('auth.basic');
Route::post('reporting/products_detailed', 'ReportsController@productsDetailed')->middleware('auth.basic');
Route::get('reporting/products_detailed/csv', 'ReportsController@productsDetailedExport')->middleware('auth.basic');

Route::get('reporting/rcpar_nps_log', 'ReportsController@rcparNpsLog')->middleware('auth.basic');
Route::post('reporting/rcpar_nps_log', 'ReportsController@rcparNpsLog')->middleware('auth.basic');
Route::get('reporting/rcpar_nps_log/csv', 'ReportsController@rcparNpsLogExport')->middleware('auth.basic');

Route::get('reporting/taxes_by_city', 'ReportsController@taxesByCity')->middleware('auth.basic');
Route::post('reporting/taxes_by_city', 'ReportsController@taxesByCity')->middleware('auth.basic');
Route::get('reporting/taxes_by_city/csv', 'ReportsController@taxesByCityExport')->middleware('auth.basic');

Route::get('reporting/intacct-report', 'ReportsController@intacctReport')->middleware('auth.basic');
Route::post('reporting/intacct-report', 'ReportsController@intacctReport')->middleware('auth.basic');
Route::get('reporting/intacct-report/csv', 'ReportsController@intacctReportExport')->middleware('auth.basic');

Route::get('api/process/{dataModel}', 'DataImportController@loadCSV')->middleware('auth.basic');

Route::resource('partners', 'PartnerProfilesController')->middleware('auth.basic');
Route::post('partners', 'PartnerProfilesController@index')->middleware('auth.basic');
Route::resource('user_profiles', 'UserProfilesController')->middleware('auth.basic');
Route::resource('orders', 'OrdersController')->middleware('auth.basic');

Route::get('/signin', 'AuthController@signin')->middleware('auth.basic');
Route::get('/ra/authorize', 'AuthController@gettoken')->middleware('auth.basic');
Route::get('/mail', 'OutlookController@mail')->name('mail')->middleware('auth.basic');

Route::get('system/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth.basic');

Route::get('/', function () {
  return redirect('dashboard');
});

app/Http/Controllers/UserProfilesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Library\Model\UserProfile;

class UserProfilesController extends Controller
{
    /**
     * Display the specified User Profile.
     *
     * @param  int $id Drupal user id (uid).
     * @return Response
     */
    public function show($uid) {
        $user = UserProfile::where('uid', $uid)->first();
        $orders = $user->getAssociatedOrders();
        $learning_stats = $user->getAssociatedLearningStats();
        return view('user_profiles.show', array(
          'user' => $user,
          'orders' => $orders,
          'learning_stats' => $learning_stats
        ));
    }
}

resources/views/user_profiles/show.blade.php
@extends('layouts.dashboard')

@section('content')

<h1>User Profile: {{ $user->first_name }} {{ $user->last_name }}</h1>

  <div class="panel panel-default">

    @if (session('status'))
    <div class="alert alert-success">
      {{ session('status') }}
    </div>
    @endif
        <div class="col-md-9">

            <div class="panel-heading">
                Learning:
            </div>
            <div class="panel-body">
                @if (count($learning_stats) > 0)
                    <table class="table table-striped task-table">
                        <!-- Table Headings -->
                        <thead>
                        <th>Product SKU</th>
                        <th>Ent</th>
                        <th>%</th>
                        <th>Restricted access</th>
                        <th>IPQ</th>
                        <th>Unlimited</th>
                        <th>Mobile offline</th>
                        <th>Expires</th>
                        </thead>
                        <tbody>
                        @foreach ($learning_stats as $l)
                            <tr>
                                <!-- Task Name -->
                                <td class="table-text">
                                    <div>{{ $l->sku }}</div>
                                </td>
                                <td class="table-text">
                                    <div>
                                        {{ $l->nid }}
                                    </div>
                                </td>
                                <td class="table-text">
                                    <div>
                                        @if ($l->viewed === NULL)
                                          n/a
                                        @elseif ($l->videos_total_duration)
                                          {{ round(($l->viewed * 100) / $l->videos_total_duration) }}%
                                        @else
                                          0%
                                        @endif
                                    </div>
                                </td>
                                <td class="table-text">
                                    <div>
                                        @if ($l->content_restricted)
                                            Yes
                                        @else
                                            No
                                        @endif
                                    </div>
                                </td>
                                <td class="table-text">
                                    <div>
                                        @if ($l->ipq_access)
                                        Yes
                                        @else
                                        No
                                        @endif
                                    </div>
                                </td>
                                <td class="table-text">
                                    <div>
                                        @if ($l->unlimited_access)
                                        Yes
                                        @else
                                        No
                                        @endif
                                    </div>
                                </td>
                                <td class="table-text">
                                    <div>
                                        @if ($l->mobile_offline_access)
                                        Yes
                                        @else
                                        No
                                        @endif
                                    </div>
                                </td>
                                <td class="table-text">
                                    <div>{{ $l->expiration_date }}</div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                    <div class="pagination">
                        {{$orders->appends([])->links()}}
                    </div>
                @endif
            </div>

            <div class="panel-heading">
                Orders:
            </div>
            <div class="panel-body">
              @if (count($orders) > 0)
                  <table class="table table-striped task-table">
                      <!-- Table Headings -->
                      <thead>
                      <th>Order ID</th>
                      <th>Amount</th>
                      <th>Status</th>
                      <th>Date</th>
                      </thead>
                      <!-- Table Body -->
                      <tbody>
                      @foreach ($orders as $o)
                          <tr>
                              <!-- Task Name -->
                              <td class="table-text">
                                  <div><a href="{{ route('orders.show', $o->order_id) }}">#{{ $o->order_id }}</a></div>
                              </td>
                              <td class="table-text">
                                  <div><a href="{{ route('orders.show', $o->order_id) }}">${{number_format($o->order_total,2)}} </a></div>
                              </td>
                              <td class="table-text">
                                  <div>{{ $o->order_status }}</div>
                              </td>
                              <td class="table-text">
                                  <div>{{date('l, F j, Y', strtotime($o->create_date))}}</div>
                              </td>
                          </tr>
                      @endforeach
                      </tbody>
                  </table>
                  <div class="pagination">
                      {{$orders->appends([])->links()}}
                  </div>
              @endif
            </div>

        </div>
        <div class="col-md-3">
            <div class="panel-heading">
                Timelines
            </div>
            <div class="panel-body">
                <table class="table table-striped task-table">
                    <tbody>
                        <tr>
                            <td class="table-text">Registered:</td>
                            <td class="table-text">{{date('d/m/Y', strtotime($user->registration_date))}}</td>
                        </tr>
                        <tr>
                            <td class="table-text">Graduation:</td>
                            <td class="table-text">{{date('d/m/Y', strtotime($user->grad_date))}}</td>
                        </tr>
                        <tr>
                            <td class="table-text">AUD Exam:</td>
                            <td class="table-text">
                            @if ($user->aud_exam_date != '0000-00-00')
                            {{date('d/m/Y', strtotime($user->aud_exam_date)) }}
                            @else
                                n/a
                            @endif
                            </td>
                        </tr>
                        <tr>
                            <td class="table-text">BEC Exam:</td>
                            <td class="table-text">
                            @if ($user->bec_exam_date != '0000-00-00')
                                {{date('d/m/Y', strtotime($user->bec_exam_date)) }}
                            @else
                                n/a
                            @endif
                            </td>
                        </tr>
                        <tr>
                            <td class="table-text">FAR Exam:</td>
                            <td class="table-text">
                            @if ($user->far_exam_date != '0000-00-00')
                                {{date('d/m/Y', strtotime($user->far_exam_date)) }}
                            @else
                                n/a
                            @endif
                            </td>
                        </tr>
                        <tr>
                            <td class="table-text">REG Exam:</td>
                            <td class="table-text">
                            @if ($user->reg_exam_date != '0000-00-00')
                                {{date('d/m/Y', strtotime($user->reg_exam_date)) }}
                            @else
                                n/a
                            @endif
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
  </div>

@endsection